apiVersion: v1
kind: ConfigMap
metadata:
  name: insights-config
  namespace: openshift-insights
data:
  config.yaml: |
    dataReporting:
        interval: 0h1m0s
        uploadEndpoint: https://console.redhat.com/api/ingress/v1/upload
        storagePath: /var/lib/insights-operator
        downloadEndpoint: https://console.redhat.com/api/insights-results-aggregator/v2/cluster/%s/reports
        conditionalGathererEndpoint: https://console.redhat.com/api/gathering/gathering_rules
        obfuscation: [workload_names networking]
    sca:
        disabled: false
        endpoint: https://api.openshift.com/api/accounts_mgmt/v1/entitlement_certificates
        interval: 0h1m0s
    alerting:
        disabled: false
    clusterTransfer:
        endpoint: https://api.openshift.com/api/accounts_mgmt/v1/cluster_transfers/
        interval: 0h1m0s
    proxy:
        httpsProxy: CHANGEME
